title: Difan Guo's Homepage
page-top-title: Difan Guo
top-section-bg-text: Journalism & Communication
home-subtitle: '<span class="text-primary" style="font-size: 1.5rem;"
copyright-text: '&copy; 2025 Difan Guo. All rights reserved.'