title: Difan Guo's Homepage
page-top-title: Difan Guo
top-section-bg-text: Journalism & Communication
home-subtitle: Difan Guo&ensp;|&ensp;郭迪帆
copyright-text: '&copy; 2025 Difan Guo. All rights reserved.'
