title: Difan Guo's Homepage
page-top-title: Difan Guo
top-section-bg-text: Journalism & Communication
home-subtitle: '<span class="text-primary" style="font-size: 1.5rem;">Difan Guo&ensp;|&ensp;郭迪帆</span><br><span class="text-primary" style="font-size: 0.8rem;">Assistant Professor, School of Journalism and Communication, South China University of Technology</span>'
copyright-text: '&copy; 2025 Difan Guo. All rights reserved.'